### ISSUE TITLE
Trouble with PCR banks on V540TU v1.0.0-rc4

### ISSUE THREAD

**Issue by wiktormowinski** [Dasharo/dasharo-issues#1491]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen

### Dasharo version

1.0.0-rc4

### Dasharo Tools Suite version

-

### Test case ID

TPMCMD001.001, TPMCMD002.001, TPMCMD003.001, TPMCMD003.002, TPMCMD004.001, MBO002.201, CBNT003.201

### Brief summary

multiple test cases report back problems with SHA1 or SHA256 checksums and PCR banks (maybe the problems are related)

### How reproducible

happens every time

### How to reproduce

try any of the tests listed above

### Expected behavior

pass

### Actual behavior

[PCR_issue.zip](https://github.com/user-attachments/files/21600011/PCR_issue.zip)
TPM tests fail to initialize SHA1 and SHA256 support variables in `TPM2 Suite Setup`
while MBO and CBNT tests have a problem with comparing checksums

**Comment by wiktormowinski** [comment]
@BeataZdunczyk may be, looks like the same problem.

**Comment by SergiiDmytruk** [comment]
`MBO002.201`, `CBNT003.201` are the same as #1476.  The rest seem to be caused by [this code](https://github.com/Dasharo/open-source-firmware-validation/blob/34fe429c3e293059dc644449115706bebb49e381/lib/tpm2.robot#L50-L52) not working properly after updating  to RF7:
```robot
    VAR    ${SHA1_ENABLED}=    ${EMPTY}    scope=SUITE
    VAR    ${SHA256_ENABLED}=    ${EMPTY}    scope=SUITE
    ${sha1_enabled}    ${sha256_enabled}=    Check Which TPM2 Banks Are Enabled
```
The variables are empty in test cases apparently because the last line doesn't assign them.  The code should probably look like this:
```robot
    ${sha1_enabled}    ${sha256_enabled}=    Check Which TPM2 Banks Are Enabled
    VAR    ${SHA1_ENABLED}=    ${sha1_enabled}    scope=SUITE
    VAR    ${SHA256_ENABLED}=    ${sha256_enabled}    scope=SUITE
```

**Comment by BeataZdunczyk** [comment]
@wiktormowinski Is this also resolved by https://github.com/Dasharo/coreboot/pull/744 or https://github.com/Dasharo/coreboot/pull/740?

**Comment by macpijan** [comment]
> I guess

Can we bring more certainty into this world?
I should be simple `yes or no` - we have had specific tests failing, now they are either passing or still failing?

**Comment by SergiiDmytruk** [comment]
That is a PCR-0 test, I think `TPMCMD*` should still be failing because RF7 handles variables differently.

**Comment by philipanda** [comment]
On a V540TU with v1.0.0-rc6 PRC0 is fine, but PCR10 always differs, but only in MBO.
MBO002 looks for me to be doing the same exact steps as CBNT002, but something surely must be different...

MBO FAILs on PRC10
[measured-boot_log.html](https://github.com/user-attachments/files/22110627/measured-boot_log.html)
[measured-boot_log.html](https://github.com/user-attachments/files/22110728/measured-boot_log.html)

CBNT PASSes
[cbnt_log.html](https://github.com/user-attachments/files/22110637/cbnt_log.html)
[cbnt_log.html](https://github.com/user-attachments/files/22110667/cbnt_log.html)

**Comment by SergiiDmytruk** [comment]
Check configuration of Linux for CONFIG_IMA.  CONFIG_IMA_MEASURE_PCR_IDX is 10 by default and Linux doesn't update event log when doing measurements.  See https://cateee.net/lkddb/web-lkddb/IMA_MEASURE_PCR_IDX.html
