### ISSUE TITLE
Connecting and immediately disconnecting the charger, sets the battery status in OS to "charging" for about 2 minutes

### ISSUE THREAD

**Issue by Pokisiekk** [Dasharo/dasharo-issues#350]
**Dasharo version**
v1.4.0

**Dasharo variant**
NV41MZ, NV41MB, NV41PZ, NS51MU, NS70MU

**Affected component(s) or functionality**
battery charge status in Ubuntu 22.04

**Brief summary**
After connecting and immediately disconnecting the charger, the battery charge status is charging about 2 minutes.

**How reproducible**
100%

**How to reproduce**

1. Power on the DUT.
2. Boot into Ubuntu 22.04.
3. Plug in and immediately plug out the charger.

**Expected behavior**
The battery charge status should indicate that battery is discharging.

**Actual behavior**
The battery charge status indicate that battery is charging about 2 minutes.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Comment by macpijan** [comment]
The `Wrong battery charge state` title seems much more scary than the actual description of the problem. I have rephrased it, so it is more accurate.

**Comment by Pace17881** [comment]
I tried to reproduce it on my nv41pz with debian bookworm and kernel 6.2.8. No issues so far. 

Maybe a ubuntu only issue?

**Comment by mkopec** [comment]
Cannot reproduce on NV4x ADL running Fedora 38, battery indicator in Waybar indicates that it's discharging as expected.

**Comment by wessel-novacustom** [comment]
@Pokisiekk I believe that this issue has been solved and/or is related to Ubuntu, not by firmware. Therefore, could you close this issue, please?

**Comment by PLangowski** [comment]
As of release `v1.7.2` this issue no longer occurs.

**Comment by PLangowski** [comment]
I just tested this and the problem does still occur on Ubuntu 22.04.  I could not, however, reproduce it on Ubuntu 23.10. This and the previous comments on this issue lead me to believe this issue is indeed Ubuntu-related. Do you think we can close this issue @macpijan?
