### ISSUE TITLE
Laptop freezes in Windows after a cold boot when the dock is attached

### ISSUE THREAD

**Issue by wessel-novacustom** [Dasharo/dasharo-issues#590]
### Device

NovaCustom NV4x-TGL

### Dasharo version

v1.7.1 (coreboot+EDK-II, public release)

### Affected component(s) or functionality

Normal functionality.

### Brief summary

Laptop freezes in Windows after a cold boot when the dock is attached

### How reproducible

75+% reproducible.

### How to reproduce

1. Boot to Windows 11 Pro x64.
2. Attach the docking station.
3. Perform a cold shutdown: Settings --> System --> Power and sleep --> Additional power settings --> Choose what power buttons do --> Change settings that are currently unavailable --> Uncheck fast startup (we do this because it's required for a dual-boot setup) --> Apply the settings.
4. Power off the laptop.
5. Start the laptop again.

### Expected behavior

The laptop boots and signs in normally and you can open any application to start your work.

### Actual behavior

The boot process is going as it should, but right at the attempt to sign in or right after signing in, the laptop freezes completely. Only a hard reset is possible.

### Additional context

The same behaviour happens on the provided test binary of today.

**Comment by macpijan** [comment]
At first, the problem description reminded me of the https://github.com/Dasharo/dasharo-issues/issues/474

**Comment by wessel-novacustom** [comment]
This problem has been reproduced on the NS70MU-i5 as well.

**Comment by mkopec** [comment]
https://github.com/Dasharo/ec/pull/53 may help here.

**Comment by miczyg1** [comment]
Fixed with: https://github.com/Dasharo/coreboot/pull/436

**Comment by wessel-novacustom** [comment]
@miczyg1 Unfortunately, it has not been fixed yet. I could still reproduce this problem on Dasharo v1.5.2-rc1 at the second attempt.

**Comment by miczyg1** [comment]
@wessel-novacustom I did 5 cold boot cycles on NV4X TGL to Windows 11 (also staying in Windows 11 doing something for at least a minute) with the dock and did not reproduce the problem. With 75%+ probability it should occurr at least once

**Comment by wessel-novacustom** [comment]
@miczyg1 I think it's related to the battery charge level as well. Now it doesn't happen anymore when the battery is fully charged ...

**Comment by wessel-novacustom** [comment]
Also, suspend mode must be set to S0ix.

**Comment by mkopec** [comment]
I'm not seeing this issue on an NV40MB unit with a Wavlink UMD05 Pro unit, will wait for the DisplayLink dock to arrive to continue testing.

**Comment by wessel-novacustom** [comment]
@mkopec And on your NV41MZ (TGL) unit with rev. e?

**Comment by wessel-novacustom** [comment]
Solved with the latest test binaries.
