### ISSUE TITLE
Display backlight hotkeys not working in Windows 11

### ISSUE THREAD

**Issue by mkopec** [Dasharo/dasharo-issues#945]
### Component

Dasharo firmware

### Device

NovaCustom V54 14th Gen, NovaCustom V56 14th Gen

### Dasharo version

v0.9.0-rc9

### Brief summary

Screen backlight hotkeys don't do anything on Windows 11

### How reproducible

100%

### How to reproduce

- boot windows 11
- press screen backlight up / down hotkeys

### Expected behavior

screen backlight brightness changes

### Actual behavior

screen backlight brightness doesn't change

**Comment by mkopec** [comment]
Should be fixed by https://github.com/Dasharo/coreboot/commit/ea0d2ab2daea6f17506c3da87aae4783db7df53d

**Comment by filipleple** [comment]
The hotkeys do work for me on v0.9.0-rc9 on V540TU with Core Ultra 7

**Comment by eatyermeat** [comment]
Hotkeys don't work with V56 core ultra 7, version 0.9.0-rc5 and Linux Mint Cinnamon 21.3

**Comment by mkopec** [comment]
I think it's dependent on the model of the internal screen, this should be fixed in the next release candidate

**Comment by eatyermeat** [comment]
Updated the rom to the newest version v0.9.0-rc10 and the  brightness hotkeys still don't work on Linux Mint Cinnamon 21.3

**Comment by wessel-novacustom** [comment]
> Updated the rom to the newest version v0.9.0-rc10 and the brightness hotkeys still don't work on Linux Mint Cinnamon 21.3

@eatyermeat It might be related to the kernel that lacks MTL drivers. Which kernel version are you running? You can check with the command `uname -r`.

It's worth to note that I couldn't reproduce this issue with the beta version of Linux Mint (22).

**Comment by eatyermeat** [comment]
I have the generic kernel 
6.5.0-41-generic

**Comment by macpijan** [comment]
> 6.5.0-41-generic

It is very or for meteor lake hardware, we should aim for 6.9 and newer.

**Comment by eatyermeat** [comment]
I had to run  the generic HWE version to get all the hardware working. When I ran a list of newer generics I saw the latest was 6.5.0.44. I don't see a 6.9 generic. When I updated to that version the backlight options now work.

**Comment by mkopec** [comment]
Many fixes for meteor lake have been included in newer kernel versions. The recommended kernel version for these devices is v6.10.
